name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r [requirements.txt](http://_vscodecontentref_/#%7B%22uri%22%3A%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FUsers%2Fcbih%2FSatoshibot%2FTGbot-for-btc-transaction.satoshi%2Frequirements.txt%22%2C%22path%22%3A%22%2FUsers%2Fcbih%2FSatoshibot%2FTGbot-for-btc-transaction.satoshi%2Frequirements.txt%22%2C%22scheme%22%3A%22file%22%7D%7D)

    - name: Run tests
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        BLOCKCYPHER_TOKEN: ${{ secrets.BLOCKCYPHER_TOKEN }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        pytest tests/ --disable-warnings
